# Generated by Django 4.2.7 on 2023-11-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='project/')),
            ],
        ),
    ]
